### ISSUE TITLE
Clash development: to-do list

### ISSUE THREAD

**Issue by Sizzlefrost** [Sizzlefrost/inter-bot#2]
- [x] Remove ctxs because they seem to be useless and we don't even have one bc it's an automatic loop _(Done, left optional CTX argument in getBans)_
- [x] Format output of getBans
- [x] Find out how riot refers to match "status" vs roster "state" _(Done, see https://discord.com/channels/713343823962701897/784087009974681650/973462987350376458)_
- [x] ~~Siz and~~
- [x] Adam need to fill in their lane's champs in globalChampionDict
- [x] Put the champion preference list into a separate file for easier editing
- [x] Error handling in `checkClashLoop` (probably just need a generic handler for all things HTTP)
- [x] Migrate key storage system onto Dotenv
- [x] Add role consideration
- [x] Add team name display on report card
- [x] Amend champion preferences to consider multirole champions
- [x] Add a mastery shout-out

**Comment by Sizzlefrost** [comment]
Helpful links

Riot's LOL documentation page
https://developer.riotgames.com/docs/lol

Riot's APIs (pointing to clash)
https://developer.riotgames.com/apis#clash-v1

An overview of interfacing with the LCU (League Client API)
https://hextechdocs.dev/getting-started-with-the-lcu-api/

The LCU's documentation
https://www.mingweisamuel.com/lcu-schema/tool/#/

Python `requests` lib: the `Response` object and what to do with it
https://www.w3schools.com/python/ref_requests_response.asp

A refresher on HTTP status codes
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by Sizzlefrost** [comment]
New patch, new todos! These are each a fairly big task in its own right.

- [x] Progress bar for clash scouting
- [ ] Live Drafting: continuously receive picks from client and update picks
- [ ] Synergy Drafting: add a synergies doc, where synergy strength will help modify champion recommendations mid-draft
- [ ] Possibly matchups
- [ ] Cache champion names and icons
